language: scala
scala:
   - 2.12.8

branches:
  # safe list
  only:
    - master
  # block list
  except:
    - /^feature.*$/

# Use container-based infrastructure
sudo: false


# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt -Dfile.encoding=UTF8 ++$TRAVIS_SCALA_VERSION test

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

